
all: src/prwd

src/prwd:
	cd src/ && make

test:
	cd src/ && make test

install: src/prwd
	install -d ${DESTDIR}${PREFIX}/bin
	install -m 755 src/prwd ${DESTDIR}${PREFIX}/bin
	install -d ${DESTDIR}${MANDIR}/man1
	install -m 644 prwd.1 ${DESTDIR}${MANDIR}/man1

clean:
	cd src/ && make clean

mantest:
	nroff -man prwd.1 | less -R

README: prwd.1
	nroff -man prwd.1 | col -b > README
