.\" Copyright (c) 2009-2014 Bertrand Janin <b@janin.com>
.\" 
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 9 2013 $
.Dt PRWD 1
.Os
.Sh NAME
.Nm prwd
.Nd print reduced working directory
.Sh SYNOPSIS
.Nm prwd
.Op Fl aVh
.Sh DESCRIPTION
.Nm
is a replacement for your shell's PS1.  It provides a number of facilities to
reduce your displayed path and allows you to add various bits of information
(e.g. current git or mercurial branch).
.Pp
The command-line options are as follows:
.Bl -tag -width Ds
.It Fl V
Show current version.
.It Fl h
Show usage.
.It Fl a
Outputs all the aliases starting with '$' as shell variable exports. The output
from this command is meant to be used with eval in your .profile file, see
section
.Nm ALIAS VARIABLES
for more detailed information.
.El
.Sh SETUP
You'll need to place this line in your ~/.profile (your mileage may vary):
.Bd -literal -offset indent
export PS1='`prwd`'
.Ed
.Sh SEE ALSO
.Xr prwdrc 5 ,
.Xr pwd 1 ,
.Xr csh 1 ,
.Xr ksh 1 ,
.Xr sh 1 ,
.Xr getcwd 3
.Sh AUTHORS
prwd was written by Bertrand Janin <b@janin.com> and is distributed under an
ISC license (BSD compatible, OSI compatible).
