# $OpenBSD$

COMMENT=	print reduced working directory

DISTNAME=	prwd-1.5
CATEGORIES=	sysutils

MAINTAINER=	Bertrand Janin <tamentis@neopulsar.org>

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	http://tamentis.com/projects/prwd/files/

WANTLIB= 		c

USE_GREFF=		Yes

#WRKDIST=	${WRKDIR}/ls
NO_REGRESS=	Yes

.include <bsd.port.mk>

